const words = {
        easy: [
          { word: "cat", hint: "A small pet animal" },
          { word: "sun", hint: "It shines in the sky" },
          { word: "pen", hint: "Used to write" },
          { word: "book", hint: "You read it" },
          { word: "dog", hint: "Barks and wags tail" },
          { word: "bat", hint: "Used in cricket" },
          { word: "hat", hint: "Worn on the head" },
          { word: "egg", hint: "Laid by a hen" },
          { word: "cup", hint: "Used to drink tea" },
          { word: "car", hint: "Has four wheels" },
          { word: "bus", hint: "Carries many people" },
          { word: "fan", hint: "Cools the room" },
          { word: "tree", hint: "Has branches and leaves" },
          { word: "milk", hint: "White drink" },
          { word: "fish", hint: "Lives in water" },
          { word: "shoe", hint: "Worn on feet" },
          { word: "cake", hint: "Sweet dessert" },
          { word: "lamp", hint: "Used for light" },
          { word: "ball", hint: "Used in many games" },
          { word: "rain", hint: "Water from clouds" },
          { word: "star", hint: "Twinkles at night" },
          { word: "bird", hint: "Can fly" },
          { word: "leaf", hint: "Part of a plant" },
          { word: "soap", hint: "Used to clean" },
          { word: "door", hint: "You open and close it" },
          { word: "wall", hint: "Part of a building" },
          { word: "bell", hint: "Makes a ringing sound" },
          { word: "snow", hint: "White and cold" },
          { word: "hand", hint: "Has five fingers" },
          { word: "tree", hint: "Has trunk and leaves" },
          { word: "girl", hint: "A female child" },
          { word: "boy", hint: "A male child" },
          { word: "rice", hint: "A grain to eat" },
          { word: "frog", hint: "Jumps in water" },
          { word: "book", hint: "Has pages" },
          { word: "nest", hint: "Home of a bird" },
          { word: "goat", hint: "Has horns and bleats" },
          { word: "duck", hint: "Quacks and swims" },
          { word: "rope", hint: "Used to tie" },
          { word: "desk", hint: "You study on it" },
          { word: "lamp", hint: "Gives light" },
          { word: "box", hint: "Used for storage" },
          { word: "kite", hint: "Flies in the sky" },
          { word: "fork", hint: "Used to eat food" },
          { word: "road", hint: "Vehicles run on it" },
          { word: "moon", hint: "Seen at night" },
          { word: "ring", hint: "Worn on finger" },
          { word: "lion", hint: "King of the jungle" },
          { word: "ship", hint: "Sails on water" },
          { word: "drum", hint: "A musical instrument" }
        ],
    medium: [
        { word: "planet", hint: "A celestial body orbiting a star" },
        { word: "marble", hint: "A type of rock or small glass ball" },
        { word: "purple", hint: "A mix of red and blue" },
        { word: "gloves", hint: "You wear them on your hands" },
        { word: "circle", hint: "A round shape" },
        { word: "ladder", hint: "You climb this" },
        { word: "button", hint: "You use this to fasten a shirt" },
        { word: "castle", hint: "A large fortified building" },
        { word: "throne", hint: "A seat for royalty" },
        { word: "pencil", hint: "Used to write or draw" },
        { word: "bucket", hint: "Used to carry liquids" },
        { word: "jungle", hint: "A dense forest" },
        { word: "bottle", hint: "Used to store liquids" },
        { word: "guitar", hint: "A stringed musical instrument" },
        { word: "shovel", hint: "Used to dig" },
        { word: "parrot", hint: "A colorful talking bird" },
        { word: "window", hint: "You look through it in a house" },
        { word: "wallet", hint: "Holds your money" },
        { word: "rocket", hint: "Launches into space" },
        { word: "hammer", hint: "Used to drive nails" },
        { word: "cheese", hint: "Made from milk" },
        { word: "wallet", hint: "Keeps your cards and cash" },
        { word: "pirate", hint: "A sea robber" },
        { word: "thread", hint: "Used for sewing" },
        { word: "rescue", hint: "To save someone" },
        { word: "saddle", hint: "Put on a horse to ride it" },
        { word: "garage", hint: "Where you park your car" },
        { word: "bridge", hint: "Crosses over a river" },
        { word: "mirror", hint: "Reflects your image" },
        { word: "camera", hint: "Takes pictures" },
        { word: "rabbit", hint: "A hopping animal with long ears" },
        { word: "packet", hint: "A small container or envelope" },
        { word: "circle", hint: "A shape with no corners" },
        { word: "napkin", hint: "Used to wipe your mouth" },
        { word: "cookie", hint: "A baked sweet treat" },
        { word: "banana", hint: "A long yellow fruit" },
        { word: "magnet", hint: "Attracts iron" },
        { word: "garden", hint: "Where flowers and plants grow" },
        { word: "jacket", hint: "Worn to keep warm" },
        { word: "wallet", hint: "Keeps cash and cards" },
        { word: "circle", hint: "Perfectly round shape" },
        { word: "helmet", hint: "Protects your head" },
        { word: "island", hint: "Land surrounded by water" },
        { word: "shower", hint: "Where you get wet and clean" },
        { word: "orange", hint: "A fruit and a color" },
        { word: "branch", hint: "Part of a tree" },
        { word: "marble", hint: "Stone or toy ball" },
        { word: "ticket", hint: "Needed to enter a movie or train" },
        { word: "castle", hint: "Fortified home of a king or queen" },
        { word: "violin", hint: "A bowed string instrument" },
        { word: "planet", hint: "Orbits a star like Earth" }
    ],
    hard: [
        { word: "algorithm", hint: "Step-by-step problem-solving procedure" },
        { word: "quadratic", hint: "Type of polynomial equation" },
        { word: "psychology", hint: "Study of the human mind" },
        { word: "neuroscience", hint: "Scientific study of the nervous system" },
        { word: "photosynthesis", hint: "Process by which plants make food" },
        { word: "parallelogram", hint: "Four-sided figure with opposite sides equal" },
        { word: "hemoglobin", hint: "Oxygen-carrying protein in red blood cells" },
        { word: "philosopher", hint: "A person who studies deep questions of life" },
        { word: "hypotenuse", hint: "Longest side of a right triangle" },
        { word: "thermodynamics", hint: "Study of heat and temperature" },
        { word: "microorganism", hint: "Tiny living being invisible to the naked eye" },
        { word: "photosensitive", hint: "Sensitive to light" },
        { word: "architecture", hint: "Art of designing buildings" },
        { word: "encyclopedia", hint: "Comprehensive book of knowledge" },
        { word: "constellation", hint: "Group of stars forming a pattern" },
        { word: "transcendental", hint: "Beyond ordinary experience or knowledge" },
        { word: "microscope", hint: "Instrument for viewing small objects" },
        { word: "respiration", hint: "Process of breathing" },
        { word: "mathematics", hint: "Study of numbers and shapes" },
        { word: "probability", hint: "Likelihood of something happening" },
        { word: "oscilloscope", hint: "Device for displaying electrical signals" },
        { word: "metamorphosis", hint: "Transformation, especially in insects" },
        { word: "photosynthesis", hint: "Plants' process of converting sunlight" },
        { word: "archaeologist", hint: "Person who studies ancient ruins" },
        { word: "hemispheres", hint: "Halves of the Earth" },
        { word: "vocabulary", hint: "Set of known words" },
        { word: "equilibrium", hint: "State of balance" },
        { word: "infrastructure", hint: "Basic physical systems of a place" },
        { word: "biochemistry", hint: "Chemistry of living things" },
        { word: "xenophobia", hint: "Fear or dislike of foreigners" },
        { word: "parliament", hint: "Legislative body of government" },
        { word: "protagonist", hint: "Main character in a story" },
        { word: "meteorology", hint: "Study of weather" },
        { word: "cartography", hint: "Science of making maps" },
        { word: "perpendicular", hint: "At a right angle" },
        { word: "synchronization", hint: "Things occurring at the same time" },
        { word: "interrogation", hint: "The act of questioning" },
        { word: "photosensitive", hint: "Reactive to light" },
        { word: "oxidization", hint: "Chemical process involving oxygen" },
        { word: "bibliography", hint: "List of books or sources" },
        { word: "caterpillar", hint: "Larval stage of a butterfly" },
        { word: "chlorophyll", hint: "Green pigment in plants" },
        { word: "hypersensitive", hint: "Extremely sensitive" },
        { word: "planetarium", hint: "Place for showing astronomy shows" },
        { word: "synchrony", hint: "Simultaneous action or development" },
        { word: "paleontology", hint: "Study of fossils" },
        { word: "articulation", hint: "Clear pronunciation of words" },
        { word: "comprehension", hint: "Understanding of information" },
        { word: "audiovisual", hint: "Related to sight and sound" }
    ]
  }
  
  